version: '3' # composeファイルのバーション指定
services:
  golang_dev:  # service名
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - ../work:/home/go_penguin/work # マウントディレクトリ指定